spring:
  security:
    user:
      name: root
      password: root
      roles: ADMIN
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=dbo
    username: sa
    password: 123456
server:
  port: 8080
security:
  oauth2:
    client:
      client-id: root
      client-secret: root
      scope: username
      registered-redirect-uri: http://www.baidu.com